Traceback (most recent call last):
  File "C:\Users\gordo\AppData\Local\pypoetry\Cache\virtualenvs\xaod-usage-w68Kx7k0-py3.9\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\gordo\AppData\Local\pypoetry\Cache\virtualenvs\xaod-usage-w68Kx7k0-py3.9\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\gordo\AppData\Local\pypoetry\Cache\virtualenvs\xaod-usage-w68Kx7k0-py3.9\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\gordo\AppData\Local\pypoetry\Cache\virtualenvs\xaod-usage-w68Kx7k0-py3.9\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\gordo\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\gordo\AppData\Local\pypoetry\Cache\virtualenvs\xaod-usage-w68Kx7k0-py3.9\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\gordo\AppData\Local\pypoetry\Cache\virtualenvs\xaod-usage-w68Kx7k0-py3.9\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\gordo\AppData\Local\pypoetry\Cache\virtualenvs\xaod-usage-w68Kx7k0-py3.9\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.hist(electrons.pt, bins=100, range=(0, 100))
plt.xlabel('Electron $p_T$ [GeV]')
plt.ylabel('Number of electrons')
_ = plt.title('Electron $p_T$ distribution for $Z\\rightarrow ee$ events')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m plt[38;5;241m.[39mhist([43melectrons[49m[38;5;241m.[39mpt, bins[38;5;241m=[39m[38;5;241m100[39m, [38;5;28mrange[39m[38;5;241m=[39m([38;5;241m0[39m, [38;5;241m100[39m))
[0;32m      2[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mElectron $p_T$ [GeV][39m[38;5;124m'[39m)
[0;32m      3[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mNumber of electrons[39m[38;5;124m'[39m)

[1;31mNameError[0m: name 'electrons' is not defined
NameError: name 'electrons' is not defined

